name: Daily Toothpaste Monitor

on:
  workflow_dispatch: # 目前我们只用手动触发测试

jobs:
  run_spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei
          pip install playwright playwright-stealth
          playwright install chromium

      - name: Run Monitor Script
        run: python main.py

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot  # 你打包下载的文件名
          path: "*.png" # 这样会打包所有的图片
